services:
  # Web Service
  - type: web
    name: dental-ai-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: starter
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: "true"
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dental-ai-db
          property: connectionString
    disk:
      name: dental-ai-storage
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1

  # PostgreSQL Database
  - type: pserv
    name: dental-ai-db
    plan: starter
    databaseName: dental_ai_production
    user: dental_ai_user

# Disk for persistent storage
disks:
  - name: dental-ai-storage
    sizeGB: 1 